# FILES
defaults:  # (these specify which config FILES to use)
  ############## TRAIN ###################################
  - train/config: splade_toy
  - train/data: pt
  - train/model: splade
  ############## INDEX ###################################
  - index: toy
  ############## RETRIEVE ################################
  - retrieve_evaluate: toy
  ############### FLOPS ##################################
  - flops: toy

# Direct PARAMETER setting
config:  # to be provided for each run
  checkpoint_dir: splade_pt_checkpoint
  index_dir: splade_pt_index
  out_dir: splade_pt_out
  fp16: false
